import type { APIRoute } from 'astro';
import { site } from '@/config/site';

/**
 * robots.txt generated at build time so the sitemap URL always matches the
 * deployed origin (which differs between the custom domain and a
 * github.io/base-path preview).
 */
export const GET: APIRoute = ({ site: astroSite }) => {
  const origin = (astroSite?.href ?? site.url).replace(/\/+$/, '');

  const body = [
    'User-agent: *',
    'Allow: /',
    '',
    '# Generated by src/pages/robots.txt.ts',
    `Sitemap: ${origin}/sitemap-index.xml`,
  ].join('\n');

  return new Response(body, {
    headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
};
