/**
 * Site-wide metadata, SEO defaults and integrations.
 *
 * ⚠️  PLACEHOLDERS — search for "TODO" and replace with your real details
 *     before going live. Nothing else in the codebase hard-codes these values.
 */

export const site = {
  /** Must match `site` in astro.config.mjs (no trailing slash). */
  url: 'https://virtualdesigner4u.com',
  name: 'Shabbar Abbas',
  /** Used in the <title> suffix and structured data. */
  brand: 'Shabbar Abbas — Web & Game Developer',
  shortName: 'VirtualDesigner4U',
  tagline: 'Websites and browser games engineered to perform.',
  description:
    'Shabbar Abbas is a senior web designer and developer with 15+ years of experience building high-performance websites, WordPress platforms and HTML5 games for clients worldwide.',
  language: 'en',
  locale: 'en_US',
  /**
   * Fallback social share image, served from /public.
   * Generated by `npm run placeholders`; replace with real 1200×630 artwork
   * before launch (social platforms will not render SVG, hence the PNG).
   */
  ogImage: '/og/default.png',
  themeColor: {
    dark: '#08090c',
    light: '#fbf9f6',
  },
  /** Default keywords; pages may append their own. */
  keywords: [
    'web designer',
    'frontend developer',
    'WordPress developer',
    'HTML5 game developer',
    'Phaser 3 developer',
    'Astro developer',
    'Tailwind CSS',
    'responsive web design',
    'website performance optimization',
    'freelance web developer Pakistan',
  ],
} as const;

/**
 * Contact form provider.
 *
 * GitHub Pages serves static files only, so the form posts directly to a
 * third-party endpoint. Swap `provider` and `endpoint` to move between
 * services — `ContactForm.astro` adapts its hidden fields automatically.
 *
 *   web3forms  → https://web3forms.com  (endpoint = access key, no account URL)
 *   formspree  → https://formspree.io/f/xxxxxxxx
 *   formsubmit → https://formsubmit.co/your@email.com
 *
 * The access key / form ID is a public, write-only identifier — it is safe to
 * commit. Never place an API secret here; this directory is publicly served.
 * Optionally override at build time with PUBLIC_FORM_ENDPOINT.
 */
export const contactForm = {
  provider: 'formspree' as 'web3forms' | 'formspree' | 'formsubmit',
  endpoint:
    import.meta.env.PUBLIC_FORM_ENDPOINT ?? 'https://formspree.io/f/mrenrolr',
  /** Subject line prefix applied to the notification email. */
  subjectPrefix: 'New enquiry from virtualdesigner4u.com',
  /** Where the user lands after a successful submit (same-site path). */
  successPath: '/contact?sent=1',
  /**
   * Honeypot field name — bots fill it, humans never see it.
   * Formspree expects `_gotcha`; Web3Forms/FormSubmit expect `botcheck`.
   */
  honeypot: '_gotcha',
} as const;

/** Optional privacy-friendly analytics. Leave `enabled: false` to ship none. */
export const analytics = {
  enabled: false,
  /** e.g. 'https://plausible.io/js/script.js' */
  scriptSrc: '',
  domain: 'virtualdesigner4u.com',
} as const;

export const seoDefaults = {
  titleTemplate: (title: string) =>
    title === 'Home' ? `${site.brand}` : `${title} · ${site.name}`,
  twitterHandle: '@shabbar_abbas', // TODO: replace or set to '' to omit.
  /** JSON-LD organisation/person identity reused across pages. */
  jsonLdId: `${site.url}/#person`,
} as const;
